[package]
name = "moss_text"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
arcstr = { workspace = true, features = ["serde"] }
bstr.workspace = true
serde = { workspace = true, features = ["derive"] }

[lints]
workspace = true