licenses = ["LICENSE-MIT"]

# Global
rust_workspace_audit.global_ignore = [
    "syn",
    "quote",
    "proc-macro2",
    "tauri-plugin-cli",
    "clap"
]

[rust_workspace_audit.crate_ignore]
desktop = [
    "tauri-plugin-shell",
    "tauri-plugin-os",
    "tauri-specta",
    "tauri-plugin-fs",
    "tauri-plugin-log",
    "tauri-plugin-global-shortcut",
    "tauri-plugin-clipboard-manager",
    "tauri-plugin-window-state"
]

xtask = [
    "cargo_metadata",
    "clap",
    "pathdiff",
    "toml"
]